[web]
100.48.6.8

[app]
10.0.11.163

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/mnt/d/Ansible/Production_Grade_Book_Review_App_Terraform+Ansible_Roles/terraform/bookreview-keypair.pem
ansible_python_interpreter=/usr/bin/python3

[app:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -i /mnt/d/Ansible/Production_Grade_Book_Review_App_Terraform+Ansible_Roles/terraform/bookreview-keypair.pem ubuntu@100.48.6.8"'

# The app server is in a private subnet and needs to be accessed via the web server as a jump host/bastion.